spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/realty_agency
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
